In [168]:
import numpy as np
import pandas as pd
import re
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')

In [169]:
data =pd.read_excel('/content/content.xlsx')

In [170]:
data.head()

Text  Label
0  affordability, convenience, honesty and integr...      1
1  Our law office understands that when people hi...      1
2  right to inherit from the adopting parent. The...      1
3                an unmarried person over age 18; or      1
4  a married person over age 18 who is legally se...      1

In [171]:
data.shape

(98, 2)

In [172]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Text    98 non-null     object
 1   Label   98 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 1.7+ KB


In [173]:
data.isnull().sum()

Text     0
Label    0
dtype: int64

In [174]:
print(data.value_counts('Label'))

Label
1    84
0    14
dtype: int64


In [175]:

from sklearn.linear_model import PassiveAggressiveClassifier

In [176]:
X=data['Text']


In [177]:
X.head()

0    affordability, convenience, honesty and integr...
1    Our law office understands that when people hi...
2    right to inherit from the adopting parent. The...
3                  an unmarried person over age 18; or
4    a married person over age 18 who is legally se...
Name: Text, dtype: object

In [178]:
y=data['Label']

In [179]:

def preprocessing_text(data):
    # Lowercase the text
    data = data.lower()
    # Remove punctuation marks and underscores
    data = re.sub(r'[^\w\s]', '', data.replace('_', ''))   #As underscores were seen so I am removing it specifically
    return data




In [180]:
X = X.apply(preprocessing_text)

In [181]:
X.head()

0    affordability convenience honesty and integrit...
1    our law office understands that when people hi...
2    right to inherit from the adopting parent the ...
3                   an unmarried person over age 18 or
4    a married person over age 18 who is legally se...
Name: Text, dtype: object

In [182]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [183]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(73,)
(73,)
(25,)
(25,)


In [184]:
X_train.head()

48    death a trust document similar to a will direc...
6     it is not until one is able to identify with t...
97    union organizing efforts administrative hearin...
80    life insurance policies that designate a benef...
75                        probate and nonprobate assets
Name: Text, dtype: object

In [185]:
y_train.head()

48    1
6     1
97    0
80    1
75    1
Name: Label, dtype: int64

In [186]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()

In [187]:
X_train=vectorizer.fit_transform(X_train) #We always fit&transform the "training" dataset and only "transform" the test dataset
X_test=vectorizer.transform(X_test)

In [188]:
print(X_train)

  (0, 144)	1
  (0, 549)	2
  (0, 179)	1
  (0, 488)	1
  (0, 537)	2
  (0, 589)	1
  (0, 165)	1
  (0, 521)	3
  (0, 551)	1
  (0, 55)	1
  (0, 174)	1
  (0, 363)	1
  (0, 432)	1
  (1, 537)	2
  (1, 521)	4
  (1, 302)	1
  (1, 301)	2
  (1, 362)	1
  (1, 564)	1
  (1, 368)	1
  (1, 4)	1
  (1, 275)	1
  (1, 591)	1
  (1, 331)	1
  (1, 278)	1
  :	:
  (72, 473)	1
  (72, 434)	1
  (72, 372)	1
  (72, 583)	1
  (72, 580)	1
  (72, 354)	1
  (72, 389)	1
  (72, 67)	1
  (72, 10)	2
  (72, 160)	1
  (72, 428)	1
  (72, 205)	1
  (72, 9)	2
  (72, 462)	1
  (72, 486)	1
  (72, 410)	1
  (72, 505)	1
  (72, 82)	1
  (72, 84)	1
  (72, 468)	1
  (72, 21)	1
  (72, 270)	2
  (72, 456)	1
  (72, 32)	1
  (72, 441)	1


In [189]:
print(X_test)

  (0, 8)	1
  (0, 26)	1
  (0, 55)	1
  (0, 70)	1
  (0, 89)	1
  (0, 144)	2
  (0, 162)	1
  (0, 172)	1
  (0, 198)	1
  (0, 255)	2
  (0, 333)	1
  (0, 337)	1
  (0, 343)	1
  (0, 363)	1
  (0, 372)	1
  (0, 399)	1
  (0, 400)	1
  (0, 407)	1
  (0, 432)	1
  (0, 503)	1
  (0, 508)	1
  (0, 520)	2
  (0, 521)	3
  (0, 522)	1
  (0, 533)	1
  :	:
  (21, 33)	1
  (21, 43)	1
  (21, 57)	1
  (21, 198)	1
  (21, 298)	1
  (21, 363)	1
  (21, 521)	1
  (22, 0)	1
  (22, 27)	1
  (22, 42)	1
  (22, 372)	1
  (22, 381)	1
  (22, 401)	1
  (23, 278)	1
  (23, 400)	1
  (23, 582)	1
  (24, 301)	1
  (24, 313)	1
  (24, 322)	2
  (24, 432)	1
  (24, 460)	2
  (24, 520)	1
  (24, 535)	1
  (24, 537)	1
  (24, 549)	1


In [190]:
X_train_array = X_train.toarray()
X_test_array = X_test.toarray()

print(X_train_array)
print(X_test_array)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 2 3 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [191]:
from sklearn.linear_model import PassiveAggressiveClassifier
classifier=PassiveAggressiveClassifier()

In [192]:
classifier.fit(X_train,y_train)

PassiveAggressiveClassifier()

In [193]:
y_pred=classifier.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1])

In [194]:
y_test

26    1
85    0
2     1
55    1
68    1
82    1
16    1
78    1
54    1
66    1
53    1
90    0
71    1
13    1
7     1
30    1
22    1
24    1
33    1
8     1
43    1
62    1
3     1
88    0
45    1
Name: Label, dtype: int64

#Checking the Performance of Model

In [195]:
from sklearn.metrics import classification_report

In [196]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.95      0.95      0.95        22

    accuracy                           0.92        25
   macro avg       0.81      0.81      0.81        25
weighted avg       0.92      0.92      0.92        25



# Testing the Model

In [197]:
sample_text1=["Freedom is misinterpreted at times. The real freedom is to allow yourself to drive deep inside yourself and believe in the freedom inside you. This will give you the confidence to deal with every situation in life."]
y_pred1=classifier.predict(vectorizer.transform(sample_text1))
if y_pred1==0:
  print('Not Plagiarised')
else:
  print("Plagiarised Content")

Plagiarised Content


In [151]:
sample_text2=["30. Poetry comes from the highest happiness or the deepest sorrow."]
y_pred2=classifier.predict(vectorizer.transform(sample_text2))
if y_pred2==1:
  print('Not Plagiarised')
else:
  print("Plagiarised Content")

Not Plagiarised


In [99]:
sample_text3=["your case. Our attorneys ensure our clients receive high-quality legal services and the support and resources they deserve. Our attorneys have more than 40 years of combined experience in the West Virginia court system:"]
y_pred3=classifier.predict(vectorizer.transform(sample_text3))
if y_pred3==0:
  print('Not Plagiarised')
else:
  print("Plagiarised Content")

Plagiarised Content


In [32]:
new_data = pd.DataFrame()
while True:
    new_text = input("Enter the new text (type 'exit' to stop): ")
    if new_text.lower() == "exit":
        break

    label = int(input("Enter the label (1 for plagiarized and 0 for not plagiarized): "))

    # Apply preprocessing steps to new_text
    

    # Add the new data to the DataFrame
    new_data = new_data.append({'Text': new_text, 'Label': label}, ignore_index=True)
    
    # Prepare the updated data for training
    X_new= new_data['Text']
    X_new = X_new.apply(preprocessing_text)
    X_update = vectorizer.transform(X_new)
    y_update = np.array(new_data['Label'])

    # Partial fit the classifier on the updated data
    classifier.partial_fit(X_update, y_update, classes=np.unique(y_train))
    print("Model Updated Successfully")


Enter the new text (type 'exit' to stop): exit


In [33]:
def check_consecutive_similarity(input_text, original_text, threshold=6):
    input_words = input_text.lower().split()
    original_words = original_text.lower().split()

    for i in range(len(input_words) - threshold + 1):
        input_consecutive_words = input_words[i:i+threshold]
        if ' '.join(input_consecutive_words) in ' '.join(original_words):
            return True

    return False












In [167]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Define the input texts
input_text = "A dream is not that which you see while sleeping, it is something that does not let you sleep."
original_text = "A dream is not that which"

# Preprocess the texts (e.g., lowercase, remove punctuation, etc.)

# Apply TF-IDF vectorization
vectorizer = TfidfVectorizer()
vectorizer.fit([input_text, original_text])
input_vector = vectorizer.transform([input_text])
original_vector = vectorizer.transform([original_text])

# Calculate cosine similarity
similarity_score = cosine_similarity(input_vector, original_vector)[0][0]

# Set the similarity threshold
similarity_threshold = 0.6

# Check if the similarity score exceeds the threshold
if similarity_score >= similarity_threshold:
    print("Plagiarised Content")
else:
    print("Not Plagiarised")


Not Plagiarised
